
/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    "_id": "1",
    "title": "Air Purifier Money Plant with pot",
    "categoryName": "Indoor",
    "season": "AllTime",
    "rating": 241,
    "discount": 29,
    "price": 249,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "2",
    "title": "Money Plant, Scindapsus (Pack of 3)",
    "categoryName": "Indoor",
    "season": "AllTime",
    "rating": 111,
    "discount": 20,
    "price": 758,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "3",
    "title": "Peace Lily, Spathiphyllum - Plant",
    "categoryName": "Indoor",
    "season": "AllTime",
    "rating": 885,
    "discount": 15,
    "price": 199,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "4",
    "title": "Top 5 Easiest to Grow Plants",
    "categoryName": "Combo",
    "season": "AllTime",
    "rating": 31,
    "discount": 25,
    "price": 1130,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "5",
    "title": "Jasminum sambac, Mogra, Arabian Jasmine - Plant",
    "categoryName": "Flowering",
    "season": "Summer",
    "rating": 913,
    "discount": 25,
    "price": 299,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "6",
    "title": "Top 3 Mosquito Repellent Plants",
    "categoryName": "Combo",
    "season": "Rainy",
    "rating": 21,
    "discount": 20,
    "price": 980,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "7",
    "title": "Parijat Tree, Parijatak, Night Flowering Jasmine - Plant",
    "categoryName": "Flowering",
    "season": "Monsoon",
    "rating": 813,
    "discount": 18,
    "price": 359,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "8",
    "title": "Top 5 Plants for Decoration on Auspicious Occasion",
    "categoryName": "Combo",
    "season": "AllTime",
    "rating": 26,
    "discount": 30,
    "price": 1236,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "9",
    "title": "Miniature Rose, Button Rose (Any Color) - Plant",
    "categoryName": "Flowering",
    "season": "Winter",
    "rating": 311,
    "discount": 25,
    "price": 299,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "10",
    "title": "Top 5 Plants to Bring Goodluck",
    "categoryName": "Combo",
    "season": "AllTime",
    "rating": 25,
    "discount": 30,
    "price": 1432,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "11",
    "title": "Jasminum sambac, Mogra, Arabian Jasmine Plant in 5 inch Pot",
    "categoryName": "Flowering",
    "season": "Summer",
    "rating": 196,
    "discount": 17,
    "price": 249,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "12",
    "title": "Top 5 Shade Tolerant Indoor Plants for Home",
    "categoryName": "Combo",
    "season": "AllTime",
    "rating": 23,
    "discount": 27,
    "price": 1349,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "13",
    "title": "Damascus Rose, Scented Rose (Any Color) - Plant",
    "categoryName": "Flowering",
    "season": "Winter",
    "rating": 772,
    "discount": 25,
    "price": 299,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "14",
    "title": "Top 4 Plants to Bring Goodluck and Prosperity",
    "categoryName": "Combo",
    "season": "AllTime",
    "rating": 20,
    "discount": 25,
    "price": 997,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "15",
    "title": "Raat Ki Rani, Raat Rani, Night Blooming Jasmine - Plant",
    "categoryName": "Flowering",
    "season": "Summer",
    "rating": 900,
    "discount": 25,
    "price": 299,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "16",
    "title": "Ixora (Pack of 3) - Plants",
    "categoryName": "Flowering",
    "season": "AllTime",
    "rating": 21,
    "discount": 20,
    "price": 858,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "17",
    "title": "Rose (Red) - Plant",
    "categoryName": "Flowering",
    "season": "Winter",
    "rating": 558,
    "discount": 25,
    "price": 299,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "18",
    "title": "Hydrangea macrophylla (Any Color) - Plant",
    "categoryName": "Flowering",
    "season": "Summer",
    "rating": 238,
    "discount": 18,
    "price": 389,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "19",
    "title": "Chlorophytum, Spider Plant - Plant",
    "categoryName": "Indoor",
    "season": "AllTime",
    "rating": 710,
    "discount": 26,
    "price": 259,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "20",
    "title": "Rajnigandha, Tuberose - Plant",
    "categoryName": "Flowering",
    "season": "Summer",
    "rating": 619,
    "discount": 17,
    "price": 249,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "21",
    "title": "Pack of 3 Good Luck Jade Plants in Ceramic Pots",
    "categoryName": "Succulent",
    "season": "AllTime",
    "rating": 249,
    "discount": 22,
    "price": 699,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "22",
    "title": "2 Layer Lucky Bamboo Plant in a Bowl with Pebbles",
    "categoryName": "Indoor",
    "season": "AllTime",
    "rating": 719,
    "discount": 26,
    "price": 259,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "23",
    "title": "Insulin Plant, Costus igneus - Plant",
    "categoryName": "Medicinal",
    "season": "AllTime",
    "rating": 704,
    "discount": 26,
    "price": 259,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "24",
    "title": "Areca Palm (Small) - Plant",
    "categoryName": "Indoor",
    "season": "AllTime",
    "rating": 277,
    "discount": 20,
    "price": 199,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "25",
    "title": "Curtain creeper, Vernonia creeper, Parda bel - Plant",
    "categoryName": "Outdoor",
    "season": "AllTime",
    "rating": 539,
    "discount": 26,
    "price": 259,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "26",
    "title": "Scented rose (Any Variety, Any Color) - Plant",
    "categoryName": "Flowering",
    "season": "Winter",
    "rating": 241,
    "discount": 25,
    "price": 299,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "27",
    "title": "Nimboo, Lemon Tree - Plant",
    "categoryName": "Fruit",
    "season": "AllTime",
    "rating": 703,
    "discount": 17,
    "price": 399,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "28",
    "title": "Areca Palm - Plant",
    "categoryName": "Indoor",
    "season": "AllTime",
    "rating": 709,
    "discount": 17,
    "price": 399,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "29",
    "title": "Anthurium (Pink) - Plant",
    "categoryName": "Flowering",
    "season": "AllTime",
    "rating": 294,
    "discount": 15,
    "price": 759,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "30",
    "title": "Pomegranate, Annar, Anar - Plant",
    "categoryName": "Fruit",
    "season": "Winter",
    "rating": 507,
    "discount": 18,
    "price": 359,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "31",
    "title": "Rose (Yellow) - Plant",
    "categoryName": "Flowering",
    "season": "Winter",
    "rating": 521,
    "discount": 25,
    "price": 299,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "32",
    "title": "Zamioculcas zamiifolia, ZZ Plant - Plant",
    "categoryName": "Indoor",
    "season": "AllTime",
    "rating": 244,
    "discount": 26,
    "price": 259,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "33",
    "title": "Zephyranthes Grandiflora, Rain Lily (Any Color) - Plant",
    "categoryName": "Flowering",
    "season": "Rainy",
    "rating": 178,
    "discount": 17,
    "price": 249,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "34",
    "title": "Origanum Majorana, Marjoram, Marwa - Plant",
    "categoryName": "Medicinal",
    "season": "Winter",
    "rating": 431,
    "discount": 20,
    "price": 299,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "35",
    "title": "Portulaca, 10 O Clock (Sunrise) - Plant",
    "categoryName": "Flowering",
    "season": "Summer",
    "rating": 271,
    "discount": 17,
    "price": 249,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "36",
    "title": "Graptoveria opalina - Succulent Plant",
    "categoryName": "Succulent",
    "season": "AllTime",
    "rating": 329,
    "discount": 26,
    "price": 259,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "37",
    "title": "Kamini - Plant",
    "categoryName": "Flowering",
    "season": "Summer",
    "rating": 290,
    "discount": 17,
    "price": 399,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "38",
    "title": "Cuphea Hyssopifolia (Lavender) - Plant",
    "categoryName": "Flowering",
    "season": "AllTime",
    "rating": 405,
    "discount": 25,
    "price": 299,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "39",
    "title": "Shevanti, Chrysanthemum (Any Color) - Plant",
    "categoryName": "Flowering",
    "season": "Winter",
    "rating": 232,
    "discount": 25,
    "price": 299,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "40",
    "title": "Aglaonema siam aurora, Aglaonema lipstick - Plant",
    "categoryName": "Indoor",
    "season": "AllTime",
    "rating": 251,
    "discount": 25,
    "price": 299,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "41",
    "title": "Money Plant Marble Queen - Plant",
    "categoryName": "Indoor",
    "season": "AllTime",
    "rating": 364,
    "discount": 17,
    "price": 249,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "42",
    "title": "Rose (Pink) - Plant",
    "categoryName": "Flowering",
    "season": "Winter",
    "rating": 372,
    "discount": 25,
    "price": 299,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "43",
    "title": "5 Lucky Bamboo Stalks (A Symbol of Positive Energy) - Gift Plant",
    "categoryName": "Indoor",
    "season": "AllTime",
    "rating": 197,
    "discount": 26,
    "price": 259,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "44",
    "title": "Miniature Rose, Button Rose (White) - Plant",
    "categoryName": "Flowering",
    "season": "Winter",
    "rating": 322,
    "discount": 25,
    "price": 299,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "45",
    "title": "Shevanti, Chrysanthemum (Pink) - Plant",
    "categoryName": "Flowering",
    "season": "Winter",
    "rating": 283,
    "discount": 11,
    "price": 299,
    "offer": true,
    "outofstock": true,
    "image": ""
  },
  {
    "_id": "46",
    "title": "Monstera obliqua - Plant",
    "categoryName": "Indoor",
    "season": "AllTime",
    "rating": 231,
    "discount": 26,
    "price": 259,
    "offer": true,
    "outofstock": true,
    "image": ""
  },
  {
    "_id": "47",
    "title": "Peperomia Magnoliifolia - Succulent Plant",
    "categoryName": "Succulent",
    "season": "AllTime",
    "rating": 252,
    "discount": 17,
    "price": 249,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "48",
    "title": "Drumsticks, Moringa Oleifera - Plant",
    "categoryName": "Medicinal",
    "season": "AllTime",
    "rating": 192,
    "discount": 25,
    "price": 299,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "49",
    "title": "Garlic Creeper, Mansoa Alliacea - Plant",
    "categoryName": "Outdoor",
    "season": "AllTime",
    "rating": 520,
    "discount": 25,
    "price": 299,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "50",
    "title": "Yellow Bamboo - Plant",
    "categoryName": "Outdoor",
    "season": "AllTime",
    "rating": 318,
    "discount": 17,
    "price": 559,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "51",
    "title": "Sempervivum Green Wheel, Houseleek, Lakshmi Kamal - Succulent Plant",
    "categoryName": "Succulent",
    "season": "AllTime",
    "rating": 176,
    "discount": 18,
    "price": 359,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "52",
    "title": "Nimboo, Lemon Tree (Seedless) - Plant",
    "categoryName": "Fruit",
    "season": "AllTime",
    "rating": 433,
    "discount": 16,
    "price": 499,
    "offer": true,
    "outofstock": true,
    "image": ""
  },
  {
    "_id": "53",
    "title": "Cassia fistula, Golden shower Tree, Bahava - Plant",
    "categoryName": "Outdoor",
    "season": "Summer",
    "rating": 346,
    "discount": 18,
    "price": 359,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "54",
    "title": "Banana - G9, Kela - Plant",
    "categoryName": "Fruit",
    "season": "AllTime",
    "rating": 376,
    "discount": 18,
    "price": 359,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "55",
    "title": "Pack of 6 Strawberry Saplings to Taste the Homegrown Magic",
    "categoryName": "Fruit",
    "season": "Winter",
    "rating": 85,
    "discount": 75,
    "price": 399,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "56",
    "title": "Neem Tree, Azadirachta indica - Plant",
    "categoryName": "Medicinal",
    "season": "AllTime",
    "rating": 359,
    "discount": 25,
    "price": 299,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "57",
    "title": "Hibiscus, Gudhal Flower (Orange) - Plant",
    "categoryName": "Flowering",
    "season": "AllTime",
    "rating": 275,
    "discount": 25,
    "price": 299,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "58",
    "title": "Top 3 Beautiful Shevanti Flowers of the Season",
    "categoryName": "Combo",
    "season": "Winter",
    "rating": 103,
    "discount": 15,
    "price": 759,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "59",
    "title": "Ashwagandha - Plant",
    "categoryName": "Medicinal",
    "season": "AllTime",
    "rating": 553,
    "discount": 11,
    "price": 199,
    "offer": true,
    "outofstock": true,
    "image": ""
  },
  {
    "_id": "60",
    "title": "Coleus (Pink) - Plant",
    "categoryName": "Outdoor",
    "season": "AllTime",
    "rating": 223,
    "discount": 17,
    "price": 249,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "61",
    "title": "Ornamental Orange Fruit (Green Leaves) - Plant",
    "categoryName": "Fruit",
    "season": "AllTime",
    "rating": 432,
    "discount": 17,
    "price": 399,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "62",
    "title": "Philodendron Scandens Oxycardium, Heart-Leaf Philodendron - Plant",
    "categoryName": "Indoor",
    "season": "AllTime",
    "rating": 212,
    "discount": 26,
    "price": 259,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "63",
    "title": "Ixora Mini Dwarf (Pink) - Plant",
    "categoryName": "Flowering",
    "season": "AllTime",
    "rating": 351,
    "discount": 26,
    "price": 259,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "64",
    "title": "Gerbera (Red) - Plant",
    "categoryName": "Flowering",
    "season": "AllTime",
    "rating": 325,
    "discount": 25,
    "price": 299,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "65",
    "title": "Mango Tree (Kesar, Grafted) - Plant",
    "categoryName": "Fruit",
    "season": "Summer",
    "rating": 350,
    "discount": 14,
    "price": 599,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "66",
    "title": "Kalanchoe (Red) - Plant",
    "categoryName": "Succulent",
    "season": "AllTime",
    "rating": 283,
    "discount": 16,
    "price": 299,
    "offer": true,
    "outofstock": true,
    "image": ""
  },
  {
    "_id": "67",
    "title": "2 Lucky Bamboo Stalks (A Symbol of Love) - Gift Plant",
    "categoryName": "Indoor",
    "season": "AllTime",
    "rating": 196,
    "discount": 26,
    "price": 259,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "68",
    "title": "Bougainvillea (Yellow) - Plant",
    "categoryName": "Flowering",
    "season": "AllTime",
    "rating": 250,
    "discount": 18,
    "price": 359,
    "offer": true,
    "outofstock": true,
    "image": ""
  },
  {
    "_id": "69",
    "title": "Set of 3 Bonsai looking Adenium Plants",
    "categoryName": "Outdoor",
    "season": "AllTime",
    "rating": 222,
    "discount": 33,
    "price": 999,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "70",
    "title": "Geranium (Any Color) - Plant",
    "categoryName": "Flowering",
    "season": "Winter",
    "rating": 247,
    "discount": 25,
    "price": 299,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "71",
    "title": "Mandevilla (Red) - Plant",
    "categoryName": "Flowering",
    "season": "Summer",
    "rating": 239,
    "discount": 12,
    "price": 499,
    "offer": true,
    "outofstock": true,
    "image": ""
  },
  {
    "_id": "72",
    "title": "Set of 4 Mixed Succulent Plants (assorted) Pack",
    "categoryName": "Succulent",
    "season": "AllTime",
    "rating": 116,
    "discount": 14,
    "price": 599,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "73",
    "title": "Graptopetalum macdougallii, Laxmi Kamal, Lakshmi Kamal - Succulent Plant",
    "categoryName": "Succulent",
    "season": "AllTime",
    "rating": 213,
    "discount": 14,
    "price": 359,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "74",
    "title": "Chikoo, Sapota, Chiku Fruit (Grafted) - Plant",
    "categoryName": "Fruit",
    "season": "AllTime",
    "rating": 310,
    "discount": 17,
    "price": 499,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "75",
    "title": "Peperomia obtusifolia - Succulent Plant",
    "categoryName": "Succulent",
    "season": "AllTime",
    "rating": 246,
    "discount": 20,
    "price": 199,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "76",
    "title": "Coleus (Green Pink) - Plant",
    "categoryName": "Outdoor",
    "season": "AllTime",
    "rating": 215,
    "discount": 17,
    "price": 399,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "77",
    "title": "Sansevieria trifasciata, Snake Plant (var. laurentii) - Plant",
    "categoryName": "Indoor",
    "season": "AllTime",
    "rating": 220,
    "discount": 17,
    "price": 399,
    "offer": true,
    "outofstock": false,
    "image": ""
  },
  {
    "_id": "78",
    "title": "Passiflora Sherry (Red) - Plant",
    "categoryName": "Flowering",
    "season": "Summer",
    "rating": 418,
    "discount": 18,
    "price": 359,
    "offer": true,
    "outofstock": true,
    "image": ""
  }
]
